//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersCatsSurprise.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowersCatsSurprise.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_black_moon_night_silhouette_outlines_32004_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_black_moon_night_silhouette_outlines_32004_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_black_snow_winter_113310_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_black_snow_winter_113310_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_black_sunlight_sitting_collar_112071_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_black_sunlight_sitting_collar_112071_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_blue_eyed_glance_113572_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_blue_eyed_glance_113572_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_box_sit_street_89346_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_box_sit_street_89346_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_branch_playful_face_105610_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_branch_playful_face_105610_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_costume_photo_shoot_89473_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_costume_photo_shoot_89473_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_dark_eyes_bright_surprisingly_25930_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_dark_eyes_bright_surprisingly_25930_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_distance_look_black_and_white_89506_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_distance_look_black_and_white_89506_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_face_eyes_photo_shoot_108794_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_face_eyes_photo_shoot_108794_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_face_eyes_photo_shoot_108794_1920x1080__1_ {
            get {
                object obj = ResourceManager.GetObject("cat_face_eyes_photo_shoot_108794_1920x1080__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_face_fluffy_blue_eyed_111951_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_face_fluffy_blue_eyed_111951_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_face_glasses_thick_65455_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_face_glasses_thick_65455_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_face_grass_lie_106391_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_face_grass_lie_106391_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_face_light_look_89216_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_face_light_look_89216_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_face_profile_fluffy_89791_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_face_profile_fluffy_89791_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_face_shouting_spotted_89372_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_face_shouting_spotted_89372_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_face_striped_close_up_89316_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_face_striped_close_up_89316_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_fluffy_grass_sit_109199_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_fluffy_grass_sit_109199_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_fluffy_hat_umbrella_104236_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_fluffy_hat_umbrella_104236_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_fluffy_ladder_113866_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_fluffy_ladder_113866_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_fluffy_walk_113818_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_fluffy_walk_113818_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_food_eat_striped_89488_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_food_eat_striped_89488_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_grass_sit_84173_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_grass_sit_84173_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_grass_sit_fear_89501_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_grass_sit_fear_89501_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_grass_walk_110252_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_grass_walk_110252_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_gray_eyes_background_89841_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_gray_eyes_background_89841_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_grin_muzzle_aggression_113567_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_grin_muzzle_aggression_113567_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_grin_scream_black_furry_113750_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_grin_scream_black_furry_113750_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_hammock_kitten_red_fluffy_96607_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_hammock_kitten_red_fluffy_96607_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_hat_face_beautiful_71803_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_hat_face_beautiful_71803_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_homeless_spotted_111769_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_homeless_spotted_111769_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_hood_fashion_gown_lying_52957_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_hood_fashion_gown_lying_52957_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_jump_spotted_89281_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_jump_spotted_89281_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_kitchen_stove_kitten_89457_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_kitchen_stove_kitten_89457_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_kitten_lying_pillow_sleep_89351_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_kitten_lying_pillow_sleep_89351_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_licking_lips_striped_89471_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_licking_lips_striped_89471_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_lies_street_113899_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_lies_street_113899_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_look_lying_89293_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_look_lying_89293_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_look_old_89296_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_look_old_89296_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_look_out_face_lie_89339_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_look_out_face_lie_89339_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_look_out_sit_dark_89764_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_look_out_sit_dark_89764_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_lying_spotted_89261_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_lying_spotted_89261_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_muzzle_blue_eyes_113456_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_muzzle_blue_eyes_113456_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_muzzle_eyes_alertness_89325_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_muzzle_eyes_alertness_89325_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_muzzle_furry_mustache_104146_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_muzzle_furry_mustache_104146_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_muzzle_lick_89489_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_muzzle_lick_89489_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_muzzle_nose_whiskers_eyes_103138_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_muzzle_nose_whiskers_eyes_103138_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_muzzle_spotted_89414_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_muzzle_spotted_89414_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_muzzle_surprise_look_89263_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_muzzle_surprise_look_89263_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_package_paper_playful_89300_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_package_paper_playful_89300_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_package_paper_playful_89388_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_package_paper_playful_89388_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_paws_lies_playful_85793_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_paws_lies_playful_85793_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_profile_muzzle_eyes_113734_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_profile_muzzle_eyes_113734_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_purebred_face_lie_89463_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_purebred_face_lie_89463_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_red_furry_sleepy_101533_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_red_furry_sleepy_101533_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_sitting_striped_89821_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_sitting_striped_89821_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_sleeping_striped_plaid_104296_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_sleeping_striped_plaid_104296_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_snow_caution_winter_89517_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_snow_caution_winter_89517_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_snow_tail_playful_climbing_52348_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_snow_tail_playful_climbing_52348_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_spotted_blur_105356_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_spotted_blur_105356_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_spotted_color_84170_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_spotted_color_84170_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_spotted_muzzle_89762_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_spotted_muzzle_89762_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_spotted_muzzle_89762_1920x1080__1_ {
            get {
                object obj = ResourceManager.GetObject("cat_spotted_muzzle_89762_1920x1080__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_striped_grass_flowers_walk_104519_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_striped_grass_flowers_walk_104519_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_striped_green_eyed_113771_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_striped_green_eyed_113771_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_striped_spotted_lying_89834_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_striped_spotted_lying_89834_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_suitcase_antiques_111415_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_suitcase_antiques_111415_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_surprise_look_striped_96597_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_surprise_look_striped_96597_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_tabby_eyes_surprise_lie_94958_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_tabby_eyes_surprise_lie_94958_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_tabby_ginger_89276_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_tabby_ginger_89276_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_tabby_walk_113727_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_tabby_walk_113727_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_tree_bark_spotted_102216_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_tree_bark_spotted_102216_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_tree_sitting_branch_111803_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_tree_sitting_branch_111803_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_trees_leaves_muzzle_106432_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_trees_leaves_muzzle_106432_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_truck_couple_kittens_89760_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_truck_couple_kittens_89760_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_walk_sit_spotted_89239_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_walk_sit_spotted_89239_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat_wet_look_104978_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("cat_wet_look_104978_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_1 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_10 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_11 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_12 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_13 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_14 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_15 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_16 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_16__1_ {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_16__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_17 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_18 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_19 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_2 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_20 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_21 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_22 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_23 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_24 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_3 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_4 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_5 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_6 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_7 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_8 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flowers_wallpaper_9 {
            get {
                object obj = ResourceManager.GetObject("flowers_wallpaper_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
