name: GitHub Actions Demo

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        cd java/AutomationTools-Series/github-actions-demo
        mvn clean test
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.3
      with:
        name: report
        path: "**/surefire-reports/TEST-*.xml"
        reporter: java-junit
